name: Build and release CLI

on:
    pull_request:
        types: [opened, synchronize]

permissions:
    contents: write
    # packages: write
    # issues: write
jobs:
    cli-integration-tests:
        name: Run tests before deployment
        uses: ./.github/workflows/run-cli-tests.yml
        secrets:
            CLI_TESTS_UA_CLIENT_ID: ${{ secrets.CLI_TESTS_UA_CLIENT_ID }}
            CLI_TESTS_UA_CLIENT_SECRET: ${{ secrets.CLI_TESTS_UA_CLIENT_SECRET }}
            CLI_TESTS_SERVICE_TOKEN: ${{ secrets.CLI_TESTS_SERVICE_TOKEN }}
            CLI_TESTS_PROJECT_ID: ${{ secrets.CLI_TESTS_PROJECT_ID }}
            CLI_TESTS_ENV_SLUG: ${{ secrets.CLI_TESTS_ENV_SLUG }}

    goreleaser:
        runs-on: ubuntu-20.04
        needs: [cli-integration-tests]
        steps:
            - name: Hello world
              run: echo "Hello, world!"
